name: kube-app
replicaCount: 1
containerName: kube-app

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: http

resources: {}

configuration: []
secrets: []
envFrom: []
storage: null

ingress:
  enabled: false

serviceAccount:
  create: false
