apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "kube-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scaling.minReplicas }}
  selector:
    matchLabels:
      {{- include "kube-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kube-app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
