apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "kube-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kube-app.serviceAccountName" . }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- range $container := (.Values.containers | default (list .Values)) }}
        - name: {{ $container.containerName }}
          image: "{{ $container.image.repository }}:{{ $container.image.tag }}"
          imagePullPolicy: {{ $container.image.pullPolicy }}
          {{- with $container.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- range $name := list "readinessProbe" "livenessProbe" "startupProbe" }}
          {{- with index $container $name }}
          {{ $name }}:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with $container.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $container.resources | nindent 12 }}
        {{- end }}
