{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | quote }}
  labels:
    {{- include "kube-app.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .data | nindent 2 }}
{{- end }}
